# This file was generated by GoReleaser. DO NOT EDIT.
cask "spice" do
  version "0.28.1"

  on_macos do
    on_arm do
      sha256 "cd262f39a988f33fdc0f81dbbfb0df532e0ea8dd130308822cd6aec89395e8b7"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8e1ce9e570cbdc7299db81125276b652c28f5c56fa29439a2bd8f724bb5140c9"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "500811db006aa3e5e973c7e8e97a09865180ab1fdaa6b9af409eb5328e13d087"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_amd64.tar.gz"
    end
  end

  name "spice"
  desc "Spice programming language."
  homepage "https://www.spicelang.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spice"
  binary "spice-bootstrap"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spice"]
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spice-bootstrap"]
  end

  # No zap stanza required

  caveats <<~EOS
    The Spice standard library is staged alongside the binary in the cask's
    staged path. If the compiler cannot locate it automatically, set:
      export SPICE_STD_DIR="$(brew --caskroom)/spice/0.28.1/std"
    The GDB pretty printers for the standard library data structures are staged next to it, at:
      $(brew --caskroom)/spice/0.28.1/tools/gdb/spice_printers.py
  EOS
end
