# This file was generated by GoReleaser. DO NOT EDIT.
cask "spice" do
  version "0.28.0"

  on_macos do
    on_arm do
      sha256 "b61d6d2eca6559b5428c79b7707096c858c59b81b4846f8ded3ebe9b13e4ea3f"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc38232e939d04919f90126c3010e84be59719f1a3b55982b778c0b410ed1bae"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9c5ff3b7e63a12fd56930ecea2fcce32c08d74140fd3baeaf4af907b4743056"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_amd64.tar.gz"
    end
  end

  name "spice"
  desc "Spice programming language."
  homepage "https://www.spicelang.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spice"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spice"]
  end

  # No zap stanza required

  caveats <<~EOS
    The Spice standard library is staged alongside the binary in the cask's
    staged path. If the compiler cannot locate it automatically, set:
      export SPICE_STD_DIR="$(brew --caskroom)/spice/0.28.0/std"
    The GDB pretty printers for the standard library data structures are staged next to it, at:
      $(brew --caskroom)/spice/0.28.0/tools/gdb/spice_printers.py
  EOS
end
