# This file was generated by GoReleaser. DO NOT EDIT.
cask "spice" do
  version "0.28.2"

  on_macos do
    on_arm do
      sha256 "cb1bb0178d3fef9499ec21507444ed592887b1307f370ff71d1c220c1cae8bb2"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32cc2ce16d76f02f11a1d82ba5cdb4dc7f79e48ef1ef5364886975396d0d1b2e"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "67ea166bea5a5869e953f0815ef639808243de0eb5cdc38de0598ec8b7ed0bbf"
      url "https://github.com/spicelang/spice/releases/download/#{version}/spice_linux_amd64.tar.gz"
    end
  end

  name "spice"
  desc "Spice programming language."
  homepage "https://www.spicelang.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spice"
  binary "spice-bootstrap"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spice"]
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spice-bootstrap"]
  end

  # No zap stanza required

  caveats <<~EOS
    The Spice standard library is staged alongside the binary in the cask's
    staged path. If the compiler cannot locate it automatically, set:
      export SPICE_STD_DIR="$(brew --caskroom)/spice/0.28.2/std"
    The GDB pretty printers for the standard library data structures are staged next to it, at:
      $(brew --caskroom)/spice/0.28.2/tools/gdb/spice_printers.py
  EOS
end
